### ISSUE TITLE
[Issue]: Not compatible with tags

### ISSUE THREAD

**Issue by yinan-c** [hkgnp/logseq-sendtothings3-plugin#1]
### Plugin Version

v0.0.2

### Logseq Version

v0.9.2

### What browsers are you seeing the problem on?

MacOS

### What happened?

As the title suggests, if I have a block like this '#test some text', the imported entry in things is empty, then, same thing happened for in-line tags, anything after the #tag is not sent to things either, also the block link misses.

Also, it seems that the graph name logseq://graph/logseq? is hard coded as "logseq" instead of the current graph.

**Comment by benjypng** [comment]
Yes, this is a bug. Will fix.

**Comment by benjypng** [comment]
Should be fixed in latest version.

**Comment by yinan-c** [comment]
It works now! Thanks for responding and fixing this so quickly!

**Comment by yinan-c** [comment]
Hi, I also wanted to ask about a new feature,  any plan to support keyboard shortcuts and/or add an entry in the command palette in Logseq (command+shift+P)?

**Comment by benjypng** [comment]
> Hi, I also wanted to ask about a new feature, any plan to support keyboard shortcuts and/or add an entry in the command palette in Logseq (command+shift+P)?

Do create a new issue for this. Thanks!
