### ISSUE TITLE
[Issue]: Feature Request: Keyboard shortcuts, command palette

### ISSUE THREAD

**Issue by yinan-c** [hkgnp/logseq-sendtothings3-plugin#2]
### Plugin Version

v0.0.3

### Logseq Version

v0.9.2

### What browsers are you seeing the problem on?

MacOS

### What happened?

A feature quest, any plan to support keyboard shortcuts and/or add an entry in the command palette in Logseq (command+shift+P)? That would be awesome!

**Comment by benjypng** [comment]
What shortcut are you thinking?
