### ISSUE TITLE
[Issue]: Feature Request, Backlink to Things

### ISSUE THREAD

**Issue by yinan-c** [hkgnp/logseq-sendtothings3-plugin#3]
### Plugin Version

v0.0.3

### Logseq Version

v0.9.2

### What browsers are you seeing the problem on?

MacOS

### What happened?

It would be good to have a backlink to things entry in logseq block, when a block is sent to things. So that we can navigate from logseq to things entry.

Like:
- some block in logseq. things://things-deeplink.

**Comment by benjypng** [comment]
Unfortunately, because Logseq crosses platforms, it's not so straightforward (afaik) to retrieve the response message from a `x-callback-url`. Will keep this at the back of my mind, but unlikely to implement.
