### ISSUE TITLE
[Issue]: Feature Request: Can child blocks be imported into Things as lists?

### ISSUE THREAD

**Issue by darthlite** [hkgnp/logseq-sendtothings3-plugin#4]
### Plugin Version

v1.0.1

### Logseq Version

v0.9.19

### What browsers are you seeing the problem on?

MacOS

### What happened?

Thanks for the plugin!

Right now when I send to Things, the block appears correctly in Things, but any child blocks appear as a jumbled mess in the notes section.

Since Things supports Markdown lists, would it be possible to import these as bullet points?

**Comment by benjypng** [comment]
Should be fixed in latest release.

**Comment by darthlite** [comment]
Many thanks!
